# Generated by Django 3.1.5 on 2021-01-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Com_app', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Com_app.query')),
            ],
        ),
    ]
