# Generated by Django 3.1.5 on 2021-01-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Com_app', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='que_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Com_app.query'),
        ),
    ]
