# Generated by Django 3.1.5 on 2021-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Com_app', '0005_auto_20210125_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='posted_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='posted_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='posted_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
